### ISSUE TITLE
Buffs given even when campfire is unlit (Fabric 1.20.1, Mod Compat Issue?)

### ISSUE THREAD

**Issue by cobbdzon** [CaoTrongThang/better-campfires-1.20.1#1]
I'm using a mod called Realistic Campfires (campfires are placed unlit and has a set duration of being lit), and when the campfire isn't lit yet it already gives out the buffs. I'm not sure of the inner workings of this mod but does it already check if the campfire is lit before it gives buffs? If not then this might be a compatibility issue with Realistic Campfires.

**Comment by cobbdzon** [comment]
https://github.com/CaoTrongThang/campfire-buffs-1.20.1/blob/f21dea365de6e3bd3d505d96912a7e153d82a095/src/main/java/com/trongthang/campfirebuff/CampfireBuff.java#L68-L75

I think the issue could be solved by adding an additional check here

**Comment by CaoTrongThang** [comment]
> https://github.com/CaoTrongThang/campfire-buffs-1.20.1/blob/f21dea365de6e3bd3d505d96912a7e153d82a095/src/main/java/com/trongthang/campfirebuff/CampfireBuff.java#L68-L75
> 
> I think the issue could be solved by adding an additional check here

Ok thanks mate, I'll try add it asap

**Comment by cobbdzon** [comment]
I've made a pull request and have tested it on my machine and it indeed works. Please review #2

**Comment by CaoTrongThang** [comment]
> I've made a pull request and have tested it on my machine and it indeed works. Please review #2

[campfirebuffs-1.2.zip](https://github.com/user-attachments/files/17606796/campfirebuffs-1.2.zip)

Thank you for the pull request, but I think it's better if I make an option (require_campfire_lit) for users to turn on and off, the default is on
