### ISSUE TITLE
Differences In Weather-Based Extinguishing

### ISSUE THREAD

**Issue by 533kr** [CaoTrongThang/better-campfires-1.20.1#5]
Currently, if a campfire is lit under any form of precipitation, it goes out instantly. Would it be possible to make that feature timer-based instead? E.g. if a fire is lit in the rain, the time it burns for is _drastically_ shortened and logs are much less effective at keeping it going, but it doesn't burn out the instant it's lit.

A config option for that would be lovely, too, especially if it could differentiate between rain and snow--right now, the fires also go out instantly in snow, but I feel like a campfire should last a little longer in snow than in direct rainfall.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified ModConfig.java to add new configuration options for rain and snow extinguish times. Updated RainExtinguishCampfireHandler.java to implement the timer-based extinguishing system with different durations for rain and snow.

You can review changes in this commit: https://github.com/lkilu6456546/CaoTrongThang-better-campfires-1.20.1-5/commit/c16c315f6667d8135edbfde56a3ddfcbf3a49962.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by CaoTrongThang** [comment]
That's easy, i'll consider it soon.

**Comment by CaoTrongThang** [comment]
Can i understand the snow, but the rain is kinda fair right?

**Comment by CaoTrongThang** [comment]
> Currently, if a campfire is lit under any form of precipitation, it goes out instantly. Would it be possible to make that feature timer-based instead? E.g. if a fire is lit in the rain, the time it burns for is _drastically_ shortened and logs are much less effective at keeping it going, but it doesn't burn out the instant it's lit.
> 
> A config option for that would be lovely, too, especially if it could differentiate between rain and snow--right now, the fires also go out instantly in snow, but I feel like a campfire should last a little longer in snow than in direct rainfall.

I just updated the Mod, including a timer-based feature for rain and snow, you can change it in the config file.
I also added if the rain or snow stops or the campfire is under any block, the timer will reset.

Close the issue to let me know it's working.

With the current, it's little weird but it should work even if the users turn off the Campfire Has Burn Time feature.

**Comment by CaoTrongThang** [comment]
Oh shit, i think i overcomplicated things, I just need to check if the campfire in rain or snow and subtract the burn time left, jesus I made a whole new config for it for no reason haha, I might fix it soon.
